# Generated by Django 5.1.4 on 2025-01-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
